import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { once } from 'node:events';

test('dashboard captures real visits/order outcomes and rejects unauthenticated money writes', async t=>{
  const dir=fs.mkdtempSync(path.join(os.tmpdir(),'mpo-product-http-'));
  process.env.MONEY_PRINTER_DATA_DIR=dir;
  process.env.DASHBOARD_PORT='0';
  process.env.DASHBOARD_HOST='127.0.0.1';
  process.env.MODE='paper';
  process.env.POLYMARKET_AUTOSTART='false';
  process.env.POLYMARKET_AUTOPILOT='false';
  process.env.PRODUCT_ECONOMICS_INGEST_TOKEN='test-only-server-secret-'.repeat(3);
  const { startDashboard }=await import('../src/dashboard.js');
  const { productEconomics }=await import('../src/productEconomics.js');
  const server=startDashboard();
  t.after(async()=>{await new Promise(resolve=>server.close(resolve));productEconomics().close();fs.rmSync(dir,{recursive:true,force:true})});
  if(!server.listening)await once(server,'listening');
  const base=`http://127.0.0.1:${server.address().port}`;
  const post=(endpoint,event,headers={})=>fetch(base+endpoint,{method:'POST',headers:{'content-type':'application/json',...headers},body:JSON.stringify(event)});
  const paid={eventId:'test-provider:1',type:'payment',userId:'test-user',currency:'USD',amountUsd:10,provider:'test-provider',reference:'test-transaction'};
  let r=await post('/api/product-economics/event',paid);
  assert.equal(r.status,401);
  r=await post('/api/product-economics/event',paid,{authorization:`Bearer ${process.env.PRODUCT_ECONOMICS_INGEST_TOKEN}`,origin:base});
  assert.equal(r.status,401);
  r=await fetch(base+'/?utm_source=pilot&utm_medium=referral');
  assert.equal(r.status,200);
  const cookie=r.headers.get('set-cookie').split(';')[0];
  await r.text();
  r=await post('/api/polymarket/paper-single',{leg:{marketId:'test-market',price:0.5},stakeUsd:1},{cookie});
  assert.equal(r.status,200);assert.equal((await r.json()).ok,true);
  r=await post('/api/polymarket/paper-single',{leg:{marketId:'test-market',price:0.5},stakeUsd:-1},{cookie});
  assert.equal(r.status,400);
  const s=await (await fetch(base+'/api/product-economics')).json();
  assert.equal(s.totals.visitors,1);assert.equal(s.totals.activatedUsers,1);assert.equal(s.totals.payingUsers,0);assert.equal(s.totals.netRevenueUsd,0);
  assert.equal(s.bySource[0].attribution.source,'pilot');
  const auth={authorization:`Bearer ${process.env.PRODUCT_ECONOMICS_INGEST_TOKEN}`};
  r=await post('/api/product-economics/event',paid,auth);assert.equal(r.status,200);assert.equal((await r.json()).duplicate,false);
  r=await post('/api/product-economics/event',paid,auth);assert.equal((await r.json()).duplicate,true);
  assert.equal((await (await fetch(base+'/api/product-economics')).json()).totals.netRevenueUsd,10);
});
