import test from 'node:test';
import assert from 'node:assert/strict';
import {policyHash,describePumpPolicy,pinPumpPolicy,decidePumpSize,evidenceGroup,auditPumpBook,outcomeMetrics,makeProfitProtocol,profitPromotionVerdict,transitionProfitCandidate,sanitizePumpSafety} from '../src/pumpProfitPolicy.js';
import {createProfitExperiments,advanceProfitExperiments,validExactQuote,profitQuoteRequests,profitExperimentView,SOL_MINT} from '../src/pumpProfitExperiments.js';
const config={tradeSizeSol:.05,riskPerTradePct:1,maxPositionSol:.15,maxTotalExposureSol:.45,minSolReserve:.02,simulatedFeeBps:25,simulatedSlippageBps:80,cooldownMin:5,openLimit:3,sizingStopPct:8};
const base=describePumpPolicy({profile:'FAIR',aggression:72,followLabBest:false},config,{tp1:12,tp2:30,stop:8,trail:7,maxHold:90});
const state=capital=>({mode:'PAPER',paperStartSol:capital,cashSol:capital,realizedLifetimePnlSol:0,positions:[],history:[],runtime:{}});
const legacy={eq:1,targetSize:.2,positionCap:.2,riskSized:.2,headroom:.45};
const mint='A'.repeat(32),pick={mint,liq:1000000,executionScore:90,score:90};
const t=1790600000000;
function quote(o,at=t+1000,slot=1,price=1){return {id:`${o.side}:${o.amountRaw}:${at}`,source:'jupiter-keyless-quote',mint:o.mint,side:o.side,inputMint:o.side==='BUY'?SOL_MINT:o.mint,outputMint:o.side==='BUY'?o.mint:SOL_MINT,inAmount:o.amountRaw,outAmount:o.side==='BUY'?String(Math.floor(Number(o.amountRaw)/1e9*100/price*1e6)):String(Math.floor(Number(o.amountRaw)/1e6*price/100*1e9)),swapMode:'ExactIn',requestedAt:at-100,receivedAt:at,contextSlot:slot,routePlan:[{swapInfo:{ammKey:'observed-pool'}}]};}
function q(o,at,slot,price){const x=quote(o,at,slot,price);x.otherAmountThreshold=x.outAmount;return x;}
function opportunity(at=t,id='first'){return {id,mint,pairAddress:'pool',priceUsd:1,solUsd:100,liquidityUsd:1e6,decimals:6,at,eligible:true,executionScore:90,integrityPassed:true,cluster:mint};}
test('small bankrolls obey cash, fees, lamport rounding and reserves',()=>{for(const capital of [.15,.25,.6458866122]){const d=decidePumpSize({legacy,state:state(capital),config,pick});assert.ok(d.sizeSol<=config.maxPositionSol);assert.ok(d.sizeSol*1.0025+.02<=capital+1e-9);assert.ok(Math.abs(d.sizeSol*1e9-Math.round(d.sizeSol*1e9))<1e-6);assert.equal(d.configuredStopIsGuaranteed,false);}assert.equal(decidePumpSize({legacy,state:state(.024),config,pick}).sizeSol,0);});
test('reconciliation and paper/live isolation fail closed',()=>{assert.throws(()=>decidePumpSize({legacy,state:{mode:'LIVE'},config,pick}),/PAPER/);const s=state(.15);s.cashSol=.2;assert.equal(decidePumpSize({legacy,state:s,config,pick}).bindingLimit,'accountingIntegrity');});
test('operator limits survive champion changes and only tighten configured ceilings',()=>{const s=state(1);s.runtime.pumpSafety={maxPositionSol:.03,maxExposureSol:.08,feeReserveSol:.04};const d=decidePumpSize({legacy,state:s,config,pick});assert.equal(d.sizeSol,.03);assert.deepEqual(sanitizePumpSafety(JSON.parse(JSON.stringify(s.runtime.pumpSafety))),s.runtime.pumpSafety);const high=state(1);high.runtime.pumpSafety={maxPositionSol:10,maxExposureSol:100};assert.equal(decidePumpSize({legacy,state:high,config,pick}).sizeSol,.15);});
test('policy hashes include sizing, ownership and immutable position exits',()=>{const p={};assert.equal(pinPumpPolicy(p,base,{migration:true,now:t}),true);const old=policyHash(p);const next=describePumpPolicy({profile:'FAIR',aggression:99},config,{tp1:100,stop:20,trail:15,maxHold:200});assert.equal(pinPumpPolicy(p,next),false);assert.equal(policyHash(p),old);assert.notEqual(describePumpPolicy({profile:'FAIR',aggression:72,followLabBest:false},{...config,tradeSizeSol:.08},{tp1:12,tp2:30,stop:8,trail:7,maxHold:90}).hash,base.hash);});
test('heuristic score and winning streak cannot authorize an adaptive increase',()=>{const s=state(10);const d=decidePumpSize({legacy:{...legacy,eq:10,targetSize:.05},state:s,config,pick,policy:{kind:'ADAPTIVE',multiplier:2},evidence:{roundTripPct:2,executionComplete:true,exitCapacitySol:1}});assert.equal(d.multiplier,1);assert.equal(d.independentlyValidated,false);assert.ok(d.reasons.includes('no-independent-group-evidence-for-increase'));});
test('loss streak reduces size rather than martingale; missing exit capacity rejects',()=>{const s=state(10);s.history=Array.from({length:3},()=>({pnlSol:-.01}));s.cashSol=9.97;s.realizedLifetimePnlSol=-.03;const evidence={state:'VALIDATED',groupHash:policyHash(evidenceGroup(pick,2)),roundTripPct:2,executionComplete:true,exitCapacitySol:1,untouched:true,independentClusters:100,afterCostLowerBound:.01,withoutBestLowerBound:.001};const d=decidePumpSize({legacy:{...legacy,eq:9.97,targetSize:.1},state:s,config,pick,policy:{kind:'ADAPTIVE',multiplier:1.5},evidence});assert.equal(d.multiplier,.5);assert.equal(d.sizeSol,.05);assert.equal(decidePumpSize({legacy,state:state(1),config,pick,policy:{kind:'ADAPTIVE'},evidence:{}}).sizeSol,0);});
test('partial sells are not independent wins; duplicate outcomes flagged',()=>{const p={id:'p',openedAt:1,closedAt:2,sizeSol:.1,remainingSol:0,pnlSol:.01,paperCashEvents:[{side:'SELL'},{side:'SELL'}]};const a=auditPumpBook({...state(.15),cashSol:.16,realizedLifetimePnlSol:.01,history:[p,p]});assert.equal(a.outcomeCount,1);assert.equal(a.wins,1);assert.equal(a.receiptCoverage.partial,1);assert.ok(a.issues.includes('duplicate-position'));assert.equal(outcomeMetrics([{pnlSol:1},{pnlSol:-.2}]).withoutBestSol,-.19999999999999996);});
test('equal-capital books do not invent missing executable fills',()=>{const protocol=makeProfitProtocol(base,.3,t),e=createProfitExperiments(protocol,base,config);advanceProfitExperiments(e,{opportunities:[opportunity()],now:t});assert.equal(e.books.length,21);for(const start of protocol.capitalsSol)assert.equal(e.books.filter(b=>b.startSol===start).length,7);assert.ok(e.books.every(b=>b.cashSol===b.startSol&&b.positions.length===0));advanceProfitExperiments(e,{now:t+31000});assert.ok(e.books.every(b=>b.positions.length===0));assert.ok(profitExperimentView(e).books.every(b=>b.netSol===null));});
test('quote matching rejects stale, wrong-size, future and missing-route evidence',()=>{const o={side:'BUY',mint,amountRaw:'10000000',submittedAt:t};const x=q(o,t+1000,1);assert.equal(validExactQuote(x,o,t+1000),true);for(const change of [{inAmount:'20000000'},{receivedAt:t+2000},{requestedAt:t-1},{routePlan:[]},{inputMint:mint},{otherAmountThreshold:'9999999999999'}])assert.equal(validExactQuote({...x,...change},o,t+1000),false);});
test('exact-size quote entry, partial exit and final close reconcile once per position',()=>{const e=createProfitExperiments(makeProfitProtocol(base,.3,t),base,config);advanceProfitExperiments(e,{opportunities:[opportunity()],now:t});let requests=profitQuoteRequests(e);advanceProfitExperiments(e,{quotes:requests.map(o=>q(o,t+1000,1)),now:t+1000});const b=e.books[0],original=b.positions[0].remainingSol;assert.ok(original>0);const tick=price=>({...opportunity(),at:t+2000,priceUsd:price});advanceProfitExperiments(e,{ticks:[tick(1.2)],now:t+2000});requests=profitQuoteRequests(e);advanceProfitExperiments(e,{quotes:requests.map(o=>q(o,t+3000,2,1.2)),now:t+3000});assert.equal(b.history.length,0);assert.ok(Math.abs(b.positions[0].remainingSol-original*.65)<1e-8);advanceProfitExperiments(e,{ticks:[{...tick(.5),at:t+4000}],now:t+4000});requests=profitQuoteRequests(e);advanceProfitExperiments(e,{quotes:requests.map(o=>q(o,t+5000,3,.5)),now:t+5000});assert.equal(b.history.length,1);assert.equal(b.positions.length,0);assert.ok(Math.abs(b.cashSol-b.startSol-b.history[0].pnlSol)<1e-9);assert.ok(b.history[0].feesSol>0);assert.equal(b.receipts.every(r=>r.allCostsKnown===false),true);});
test('same pool and slot are not reused for simultaneous liquidity',()=>{const e=createProfitExperiments(makeProfitProtocol(base,.3,t),base,config);advanceProfitExperiments(e,{opportunities:[opportunity()],now:t});const requests=profitQuoteRequests(e);for(const b of e.books)b.usedPoolSlots.push('observed-pool:1');advanceProfitExperiments(e,{quotes:requests.map(o=>q(o,t+1000,1)),now:t+1000});assert.ok(e.books.every(b=>b.positions.length===0));assert.ok(e.books[0].rejections['same-pool-slot-capacity-already-used']);});
test('chronology, holdout blinding, mint purging and bounded entry work',()=>{const protocol=makeProfitProtocol(base,.3,t),e=createProfitExperiments(protocol,base,config);advanceProfitExperiments(e,{opportunities:[opportunity()],now:t});assert.throws(()=>advanceProfitExperiments(e,{now:t-1}),/backwards/);advanceProfitExperiments(e,{opportunities:[opportunity(protocol.validation.start,'heldout')],now:protocol.validation.start});assert.equal(e.books[0].opportunities,0);assert.equal(profitExperimentView(e).holdoutBlinded,true);assert.equal(profitExperimentView(e).books[0].netSol,null);advanceProfitExperiments(e,{now:protocol.validation.end+1});assert.equal(e.status,'BATCH_CLOSED_AWAITING_EVIDENCE_REVIEW');});
test('unqualified promotion is refused; canary requires every gate; rollback restores baseline',()=>{const protocol=makeProfitProtocol(base,.3,t),reference={startSol:.15,netSol:.01,withoutBestSol:.001,drawdownPct:5};const validation={datasetHash:'sealed-once',untouched:true,clusterPurged:true,start:protocol.validation.start,end:protocol.validation.end,positions:120,clusters:60,executionComplete:true,allCostsKnown:true,openPositions:0,missingObservations:0,pairedLowerBoundSol:.001,candidateCount:7,familyAdjustedAlpha:.05};const candidate={mode:'PAPER',policyHash:'candidate',protocolHash:protocol.hash,baselineHash:protocol.baselineHash,startSol:.15,netSol:.02,withoutBestSol:.005,drawdownPct:5,validation,stress:Object.fromEntries(protocol.stress.map(k=>[k,{passed:true}]))};const options={candidate,baseline:reference,protocol,now:protocol.validation.end+1};assert.equal(profitPromotionVerdict(candidate,reference,protocol,options).qualified,true);assert.equal(transitionProfitCandidate({},'PAPER_CANARY',options).state,'PAPER_CANARY');assert.equal(profitPromotionVerdict(candidate,reference,protocol,{...options,usedHoldouts:['sealed-once']}).qualified,false);assert.equal(profitPromotionVerdict({...candidate,validation:{...validation,allCostsKnown:false}},reference,protocol,options).qualified,false);assert.equal(transitionProfitCandidate({},'ROLLBACK',options).state,'BASELINE');assert.equal(transitionProfitCandidate({},'ACTIVE',options).lastRejectedPromotion.reasons[0],'active-champion-replacement-requires-independent-canary-validation');});
