import test from 'node:test';
import assert from 'node:assert/strict';
import {CROWD_SCHEMA,CROWD_LIMITS,CROWD_HORIZON_MS,normalizeCrowdEvent,emptyCrowdCapture,appendCrowdCapture,sealCrowdRecord,validCrowdRecord,episodeCoverage,crowdControl,crowdPhase,crowdHash,assertCrowdPaper} from '../src/crowdContract.js';
import {inferCrowdModel,chooseCrowdAction,clusteredInterval,evaluateCrowdComparison} from '../src/crowdResearch.js';
const t=1790600000000;
function raw({at=t,wallet='leader',asset='asset',id='tx',side='BUY',sol=1,extra={}}={}){return {signature:id,eventIndex:0,ts:at,slot:Math.floor(at/400),mint:asset,wallet,tokenDelta:side==='BUY'?100:-100,solDelta:side==='BUY'?-sol:sol,source:'deterministic-fixture',raw:{signer:true,program:'pump',firstObservedAt:at+1000,ingestedAt:at+1000,confirmation:'finalized',changedAssets:[asset],tokenDecimals:6,feeSol:.000005,...extra}};}
function windowFor(asset,from,to,at){return {asset,fromTs:from,toTs:to,observedAt:at,scope:'ASSET_MINT_REFERENCES',complete:true,commitment:'finalized',gaps:[]};}
function repeated({common=false,related=false}={}){
 const c=emptyCrowdCapture(t-1000000),now=t+10000000;
 for(let i=0;i<8;i++){const at=t+i*600000,asset='token'+i,rows=[raw({at,id:'lead'+i,asset,extra:common?{commonSignalId:'macro'}:{}}),raw({at:at+90000,wallet:'follower',asset,id:'follow'+i,sol:2,extra:related?{relatedGroup:'group'}:{}})];
  if(related)rows.push(raw({at:at+95000,wallet:'related-follower',asset,id:'related'+i,sol:2,extra:{relatedGroup:'group'}}));
  appendCrowdCapture(c,rows,null,{now});c.windows.push(windowFor(asset,at-120000,at+120000,now));
 }
 const outcomes=Array.from({length:16},(_,i)=>({wallet:'leader',phase:'TRAIN',closedAt:t+9000000,decisionAt:t+1000,firstObservedAt:t+1000,fillAt:t+2000,returnPct:20+i%3,cluster:'token'+(i%8),entryChasePct:0,detectionDelayMs:1000,allCostsKnown:true}));
 return {capture:sealCrowdRecord(c),model:inferCrowdModel(sealCrowdRecord(c),{asOf:now,copyOutcomes:outcomes}),now,outcomes};
}
function decisionFixture(){const x=repeated(),at=x.now-10000,e=normalizeCrowdEvent(raw({at,id:'forward',asset:'forward'}),{now:x.now}).event;return {...x,event:e,windows:[windowFor(e.asset,at-120000,at,x.now)],quote:{priceSol:e.price,capacitySol:100,observedAt:x.now,latencyMs:1000}};}
test('normalized records preserve separate clocks, finality, provenance and currency',()=>{const n=normalizeCrowdEvent(raw(),{now:t+2000});assert.ok(n.ok);assert.equal(n.event.firstObservedAt,t+1000);assert.equal(n.event.sourceAt,t);assert.equal(n.event.quoteCurrency,'SOL');assert.equal(n.event.decimals,6);assert.equal(n.event.provenance.allCostsKnown,false);assert.equal(n.event.transactionOrder,null);});
test('historical-only, future, failed, transfer, multi-asset and create transactions do not invent profit',()=>{for(const x of [raw({extra:{firstObservedAt:undefined}}),raw({extra:{firstObservedAt:t+5000,ingestedAt:t+5000}}),{...raw(),failed:true},raw({extra:{program:'other'}}),raw({extra:{changedAssets:['asset','other']}}),raw({extra:{createTx:true}}),{...raw(),solDelta:1}])assert.equal(normalizeCrowdEvent(x,{now:t+2000}).ok,false);});
test('reconnect dedupe keeps FIRST observation; conflicting economics invalidate without rewriting',()=>{const c=emptyCrowdCapture(t);appendCrowdCapture(c,[raw()],null,{now:t+2000});appendCrowdCapture(c,[raw({extra:{firstObservedAt:t+5000,ingestedAt:t+5000}})],null,{now:t+6000});assert.equal(c.events.length,1);assert.equal(c.events[0].firstObservedAt,t+1000);assert.equal(c.duplicates,1);appendCrowdCapture(c,[raw({sol:2})],null,{now:t+7000});assert.equal(c.events[0].notional,1);assert.equal(c.invalidatedIds.length,1);assert.equal(c.status,'INTEGRITY_BLOCKED');});
test('missing interval, leader-only feed, nonfinality and future windows cannot claim coverage',()=>{const w=windowFor('a',t,t+1000,t+2000);assert.equal(episodeCoverage([w],'a',t,t+1000,t+2000).ok,true);for(const changed of [{scope:'LEADER_ONLY'},{complete:false},{commitment:'confirmed'},{gaps:['reconnect']},{observedAt:t+3000}])assert.equal(episodeCoverage([{...w,...changed}],'a',t,t+1000,t+2000).ok,false);assert.equal(episodeCoverage([w,{...w,fromTs:t+2000,toTs:t+4000}],'a',t,t+4000,t+5000).ok,false);});
test('byte-level contract integrity and real-order refusal fail closed',()=>{const c=sealCrowdRecord(emptyCrowdCapture(t));assert.ok(validCrowdRecord(c));c.mode='LIVE';assert.equal(validCrowdRecord(c),false);assert.throws(()=>assertCrowdPaper(c),/live execution/);assert.throws(()=>assertCrowdPaper({...emptyCrowdCapture(t),liveExecutionAllowed:true}),/live execution/);});
test('repeated follower inference uses distinct assets and clusters, not subscriber counts',()=>{const {model}=repeated(),w=model.candidates.find(w=>w.wallet==='leader');assert.equal(w.eligibleEpisodes,8);assert.equal(w.independentClusters,8);assert.equal(w.assets,8);assert.equal(w.relationships[0].episodes,8);assert.equal(w.watcherCount,null);assert.equal(w.delayMedianMs,90000);assert.ok(w.incrementalFlowSol.lower>0);assert.equal(w.copyRealizable.clusters,8);});
test('common-signal fixture cannot be labeled a causal or profitable follower effect',()=>{const {model}=repeated({common:true}),w=model.candidates.find(w=>w.wallet==='leader');assert.equal(w.confoundedEpisodes,8);assert.equal(w.incrementalFlowSol.lower,null);assert.equal(w.relationships.length,0);assert.match(model.caveat,/not causation/);});
test('related addresses increase address count but collapse economic concentration',()=>{const {model}=repeated({related:true}),w=model.candidates.find(w=>w.wallet==='leader');assert.equal(w.observedFollowerAddresses,2);assert.equal(w.concentrationHhi,1);assert.equal(w.watcherCount,null);});
test('model inference does not mutate raw capture or use future receipts/outcomes',()=>{const {capture,now,outcomes}=repeated(),hash=crowdHash(capture);inferCrowdModel(capture,{asOf:now,copyOutcomes:outcomes});assert.equal(crowdHash(capture),hash);const m=inferCrowdModel(capture,{asOf:t-1,copyOutcomes:outcomes});assert.equal(m.coverage.observedEvents,0);assert.equal(m.candidates.length,0);});
test('null/too-small evidence keeps uncertainty unknown; followers are not independent trials',()=>{const ci=clusteredInterval([{cluster:'same',value:1},{cluster:'same',value:5}]);assert.equal(ci.clusters,1);assert.equal(ci.lower,null);assert.equal(ci.mean,3);});
test('early follow requires positive copy-realizable evidence and remaining flow',()=>{const x=decisionFixture();assert.equal(chooseCrowdAction(x).action,'EARLY_FOLLOW');assert.equal(chooseCrowdAction({...x,now:x.now+121000}).action,'AVOID');});
test('crowded flow relative to observed exit capacity is rejected, not automatically shorted',()=>{const x=decisionFixture(),r=chooseCrowdAction({...x,quote:{...x.quote,capacitySol:.01}});assert.equal(r.action,'AVOID');assert.match(r.reason,/EXIT_CAPACITY/);assert.notEqual(r.action,'CONFIRMED_REVERSAL');});
test('unknown costs, stale/missing evidence, and source sells legitimately produce NO_TRADE',()=>{const x=decisionFixture();assert.equal(chooseCrowdAction({...x,quote:null}).action,'NO_TRADE');assert.equal(chooseCrowdAction({...x,windows:[]}).action,'NO_TRADE');assert.equal(chooseCrowdAction({...x,event:{...x.event,side:'SELL'}}).action,'NO_TRADE');const m=structuredClone(x.model);m.candidates.find(w=>w.wallet==='leader').copyRealizable.allCostsKnown=false;assert.equal(chooseCrowdAction({...x,model:sealCrowdRecord(m)}).reason,'COPY_OUTCOMES_HAVE_UNMEASURED_EXECUTION_COSTS');});
test('profitable historical copying is not proof a much higher current entry remains profitable',()=>{const x=decisionFixture();const r=chooseCrowdAction({...x,quote:{...x.quote,priceSol:x.quote.priceSol*3}});assert.equal(r.action,'WAIT');assert.ok(r.expectedNetReturnPct<0);});
test('a reversal that never confirms never creates a reversal or unsupported short',()=>{const x=decisionFixture();for(let i=0;i<10;i++)assert.notEqual(chooseCrowdAction({...x,now:x.now+i*10000,quote:{...x.quote,priceSol:x.quote.priceSol*(1+i/4),observedAt:x.now+i*10000}}).action,'CONFIRMED_REVERSAL');});
test('mode changes need explicit paper opt-in and reject live/invented modes',()=>{assert.equal(crowdControl().mode,'SHADOW_COMPARISON');assert.throws(()=>crowdControl({mode:'PAPER_EXPERIMENT'}),/Explicit/);assert.equal(crowdControl({mode:'PAPER_EXPERIMENT',confirmation:'START ISOLATED PAPER EXPERIMENT'}).mode,'PAPER_EXPERIMENT');assert.throws(()=>crowdControl({mode:'LIVE'}),/Unknown/);assert.throws(()=>crowdControl({budgetSol:100}),/capital/);});
test('event budget does not fabricate discarded observations',()=>{const c=emptyCrowdCapture(t);c.events=Array.from({length:CROWD_LIMITS.events},(_,i)=>({id:'old'+i}));appendCrowdCapture(c,[raw()],null,{now:t+2000});assert.equal(c.events.length,CROWD_LIMITS.events);assert.equal(c.status,'EVENT_BUDGET_SPENT');});
test('chronological phases have explicit embargo and sealed holdout boundaries',()=>{const p={train:{end:10},validation:{start:20,end:30},holdout:{start:40,end:50}};assert.deepEqual([5,15,25,35,45,55].map(t=>crowdPhase(p,t)),['TRAIN','EMBARGO','VALIDATION','EMBARGO','HOLDOUT','SEALED']);});
test('empty or huge variant count cannot qualify a crowd policy',()=>{const study={schema:CROWD_SCHEMA,mode:'PAPER',liveExecutionAllowed:false,protocol:sealCrowdRecord({holdout:{end:t+10000}}),baseline:sealCrowdRecord({capital:.15}),outcomes:[],variants:1e9};const r=evaluateCrowdComparison(study,t);assert.equal(r.qualified,false);assert.ok(r.blockers.includes('NO_ESTABLISHED_INCREMENTAL_EDGE'));assert.ok(r.blockers.includes('UNTOUCHED_HOLDOUT_NOT_SEALED'));});
test('ablations preserve unknown stress evidence and show influence rather than fake approvals',async()=>{
 const {crowdAblationDiagnostics}=await import('../src/crowdResearch.js');
 const pairs=Array.from({length:8},(_,i)=>({eventId:'e'+i,cluster:'asset'+i,asset:'asset'+i,wallet:'w'+i,complete:true,pnlSol:.1,copyDelta:.05,baselineDelta:.04,filterDelta:.02,results:{CROWD_AWARE:{sizeSol:.01}}}));
 const d=crowdAblationDiagnostics(pairs);assert.ok(d.followerModelIncrement.versusCopy.lower>0);assert.equal(d.removeLargestWallet.samples,7);assert.equal(d.removeBestOutcome.samples,7);assert.equal(d.doubleLatency.passed,false);assert.equal(d.higherCosts.passed,false);
});
