import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
const root=fs.mkdtempSync(path.join(os.tmpdir(),'mpo-crowd-runtime-'));process.env.MONEY_PRINTER_DATA_DIR=root;process.env.MODE='paper';process.env.POLYMARKET_AUTOSTART='false';process.env.MPO_COMPUTE_BUDGET_FILE=path.join(root,'compute.json');
const {describePumpPolicy}=await import('../src/pumpProfitPolicy.js');
const {createCrowdStudy,advanceCrowdStudy,crowdStudyRequests,crowdStudyView,availableQuote}=await import('../src/crowdStudy.js');
const {captureCrowdEvents,loadCrowdCapture,setCrowdControl,crowdRuntimeView}=await import('../src/crowdRuntime.js');
const {pullMint,parseSwapEvents}=await import('../src/transactionIndexer.js');
const {sealCrowdRecord,CROWD_SCHEMA,normalizeCrowdEvent,crowdHash}=await import('../src/crowdContract.js');
const {SOL_MINT}=await import('../src/pumpProfitExperiments.js');
const {collectPumpProfitQuotes}=await import('../src/pumpProfitQuotes.js');
const {MarketAdapter,OrderSimulator,FrictionModel}=await import('../src/core/paperTrading.js');
const config={tradeSizeSol:.05,riskPerTradePct:1,maxPositionSol:.15,maxTotalExposureSol:.45,minSolReserve:.02,simulatedFeeBps:25,simulatedSlippageBps:80,cooldownMin:5,openLimit:3,sizingStopPct:8};
const policy=describePumpPolicy({profile:'FAIR',aggression:72,followLabBest:false},config,{tp1:12,tp2:30,stop:8,trail:7,maxHold:90});
const t=1790600000000,mint='A'.repeat(32),pool='B'.repeat(32);
const raw=()=>({signature:'forward-source',eventIndex:0,ts:t,slot:100,mint,wallet:'leader',tokenDelta:100,solDelta:-1,source:'fixture',raw:{signer:true,program:'pump',firstObservedAt:t+1000,ingestedAt:t+1000,confirmation:'finalized',changedAssets:[mint],tokenDecimals:6,feeSol:.000005}});
const event=()=>normalizeCrowdEvent(raw(),{now:t+2000}).event;
const market=(at=t+2000,price=1)=>({mint,pairAddress:pool,priceUsd:price,solUsd:100,liquidityUsd:1e6,liq:1e6,decimals:6,at,eligible:true,executionScore:90,integrityPassed:true,cluster:mint});
function quote(o,at,slot=1,price=1){const out=o.side==='BUY'?String(Math.floor(Number(o.amountRaw)/1e9*100/price*1e6)):String(Math.floor(Number(o.amountRaw)/1e6*price/100*1e9));return {id:`${o.side}:${o.amountRaw}:${at}`,source:'jupiter-keyless-quote',mint:o.mint,side:o.side,inputMint:o.side==='BUY'?SOL_MINT:o.mint,outputMint:o.side==='BUY'?o.mint:SOL_MINT,inAmount:o.amountRaw,outAmount:out,otherAmountThreshold:out,swapMode:'ExactIn',requestedAt:at-100,receivedAt:at,contextSlot:slot,routePlan:[{swapInfo:{ammKey:pool}}]};}
const study=()=>createCrowdStudy({policy,config,capitalSol:.15,now:t});
function openDirect(s,price=2){advanceCrowdStudy(s,{events:[event()],markets:[market()],incumbentPolicyHash:policy.hash,now:t+2000});const requests=crowdStudyRequests(s,t+2000).requests;assert.ok(requests.length>0,'benchmark request exists');const quotes=requests.map(o=>quote(o,t+4000,1,price));advanceCrowdStudy(s,{markets:[market(t+4000,price)],quotes,now:t+4000});const b=s.cohorts[0].books.find(b=>b.candidateId==='DIRECT_COPY');assert.equal(b.positions.length,1);return b;}
test('isolated baseline, direct, crowd and filter books use equal capital; incumbent is untouched',()=>{const s=study(),baselineHash=crowdHash(s.baseline);advanceCrowdStudy(s,{events:[event()],markets:[market()],incumbentPolicyHash:policy.hash,now:t+2000});assert.equal(s.cohorts[0].books.length,4);assert.ok(s.cohorts[0].books.every(b=>b.startSol===.15));assert.equal(crowdHash(s.baseline),baselineHash);assert.equal(s.decisions[0].action.action,'NO_TRADE');assert.equal(s.cohorts[0].books.find(b=>b.candidateId==='CROWD_AWARE').pending.length,0);});
test('profitable leader move can lose for a delayed copy after entry price doubles',()=>{const s=study(),b=openDirect(s,2);assert.equal(b.positions[0].entryPrice,2);assert.ok(b.positions[0].openedAt>=event().firstObservedAt);advanceCrowdStudy(s,{markets:[market(t+5000,1.5)],now:t+5000});const requests=crowdStudyRequests(s,t+5000).requests.filter(x=>x.side==='SELL');assert.ok(requests.length);advanceCrowdStudy(s,{markets:[market(t+6000,1.5)],quotes:requests.map(o=>quote(o,t+6000,2,1.5)),now:t+6000});assert.equal(b.history.length,1);assert.ok(b.history[0].pnlSol<0);assert.ok(1.5>1,'leader price rose while delayed copy lost');assert.ok(Math.abs(b.cashSol-b.startSol-b.history[0].pnlSol)<1e-9);assert.equal(s.outcomes.find(o=>o.policy==='DIRECT_COPY').allCostsKnown,false);});
test('quote before our submission delay cannot fill, even if the leader traded earlier',()=>{const s=study();advanceCrowdStudy(s,{events:[event()],markets:[market()],incumbentPolicyHash:policy.hash,now:t+2000});const requests=crowdStudyRequests(s,t+2000).requests;advanceCrowdStudy(s,{quotes:requests.map(o=>quote(o,t+2500)),now:t+2500});assert.ok(s.cohorts[0].books.every(b=>!b.positions.length));assert.ok(requests.every(r=>r.submittedAt>=t+3500));});
test('experimental positions stay managed after Observe Only and after entry budget is exhausted',()=>{const s=study(),b=openDirect(s,2);s.decisions=Array.from({length:512},(_,i)=>({eventId:'dummy'+i}));advanceCrowdStudy(s,{control:{mode:'OBSERVE_ONLY'},markets:[market(t+5000,1.5)],now:t+5000});assert.equal(s.budgetSpent,true);assert.ok(b.pending.some(o=>o.side==='SELL'));const requests=crowdStudyRequests(s,t+5000).requests.filter(o=>o.side==='SELL');advanceCrowdStudy(s,{control:{mode:'OBSERVE_ONLY'},markets:[market(t+6000,1.5)],quotes:requests.map(o=>quote(o,t+6000,2,1.5)),now:t+6000});assert.equal(b.positions.length,0);assert.equal(b.history.length,1);});
test('Observe Only and global risk stop cancel entries without relabeling old cohorts',()=>{for(const control of [{mode:'OBSERVE_ONLY'},{mode:'SHADOW_COMPARISON'}]){const s=study();advanceCrowdStudy(s,{events:[event()],markets:[market()],incumbentPolicyHash:policy.hash,now:t+2000});advanceCrowdStudy(s,{control,entryAllowed:false,now:t+2500});assert.equal(crowdStudyRequests(s,t+2500).requests.filter(r=>r.side==='BUY').length,0);assert.equal(s.cohorts[0].operatorMode,'SHADOW_COMPARISON');}});
test('duplicate scanner/copy events and incumbent paper exposure cannot multiply positions',()=>{const s=study();advanceCrowdStudy(s,{events:[event(),event()],markets:[market()],incumbentPolicyHash:policy.hash,now:t+2000});assert.equal(s.decisions.length,1);const p=study();advanceCrowdStudy(p,{events:[event()],markets:[market()],incumbentPositions:[{mint}],control:{mode:'PAPER_EXPERIMENT'},incumbentPolicyHash:policy.hash,now:t+2000});assert.equal(p.decisions[0].eligible,false);assert.ok(p.cohorts[0].books.every(b=>b.pending.length===0));});
test('entry size never masquerades as executable exit capacity',()=>{const e=event(),buy=quote({mint,side:'BUY',amountRaw:'10000000'},t+4000),sell=quote({mint,side:'SELL',amountRaw:buy.otherAmountThreshold},t+5000,2,.9);assert.equal(availableQuote(e,market(),[buy],t+5000),null);const q=availableQuote(e,market(),[buy,sell],t+5000);assert.ok(q);assert.ok(q.capacitySol<.01);assert.equal(q.exitQuoteId,sell.id);assert.equal(availableQuote(e,market(),[buy,{...sell,inAmount:'1'}],t+5000),null);});
test('new live modes and baseline tampering are refused before any book work',()=>{const s=study();assert.throws(()=>advanceCrowdStudy({...s,mode:'LIVE'}),/live/);s.baseline.capitalSol=100;assert.throws(()=>advanceCrowdStudy(s),/integrity/);});
test('holdout results remain blinded and earlier assets are purged',()=>{const s=study();advanceCrowdStudy(s,{events:[event()],markets:[market()],now:t+2000});const now=s.protocol.holdout.start+1000,e={...event(),id:'later',sourceAt:now-500,firstObservedAt:now,ingestedAt:now};s.priorAssets=[mint];advanceCrowdStudy(s,{events:[e],markets:[market(now)],incumbentPolicyHash:policy.hash,now});assert.equal(s.decisions.at(-1).reason,'PURGED_HELDOUT_ASSET');const v=crowdStudyView(s,now);assert.equal(v.holdoutBlinded,true);assert.ok(v.books.filter(b=>b.phase==='HOLDOUT').every(b=>b.cashSol===null&&b.realizedNetSol===null));});
test('journal recovery restores first-observed timestamps and duplicates after lost checkpoint',()=>{const dir=fs.mkdtempSync(path.join(root,'journal-'));captureCrowdEvents([raw()],null,{dir,now:t+2000});captureCrowdEvents([raw()],null,{dir,now:t+3000});fs.unlinkSync(path.join(dir,'wallet-crowd-capture.json'));const c=loadCrowdCapture(dir,t+4000);assert.equal(c.events.length,1);assert.equal(c.duplicates,1);assert.equal(c.events[0].firstObservedAt,t+1000);assert.equal(c.frameSequence,2);});
test('corrupted evidence is blocked instead of silently reset; immutable capital cannot be changed',()=>{const dir=fs.mkdtempSync(path.join(root,'bad-'));captureCrowdEvents([raw()],null,{dir,now:t+2000});const file=path.join(dir,'wallet-crowd-capture.json'),c=JSON.parse(fs.readFileSync(file));c.events[0].price=999;fs.writeFileSync(file,JSON.stringify(c));assert.throws(()=>loadCrowdCapture(dir,t+3000),/checksum/);fs.writeFileSync(path.join(dir,'wallet-crowd-baseline.json'),JSON.stringify(sealCrowdRecord({capitalSol:.15})));assert.throws(()=>setCrowdControl({budgetSol:.2},{dir}),/frozen/);setCrowdControl({mode:'OBSERVE_ONLY'},{dir});assert.equal(crowdRuntimeView(dir).control.mode,'OBSERVE_ONLY');});
function tx(signature='good'){return {version:1,blockTime:t/1000,slot:100,transaction:{signatures:[signature],message:{accountKeys:[{pubkey:'leader',signer:true},{pubkey:'token-account',signer:false}],instructions:[{programId:'6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P'}]}},meta:{err:null,fee:5000,preBalances:[100000000000,2039280],postBalances:[98999995000,2039280],preTokenBalances:[],postTokenBalances:[{accountIndex:1,mint,owner:'leader',uiTokenAmount:{amount:'100000000',decimals:6}}]}};}
test('v1 finalized indexer persists earlier transaction receipts when later RPC throws',async()=>{const m={mint,cursorSig:null},emitted=[];await assert.rejects(pullMint(m,{c:{sigPages:1,txPerPull:25},now:()=>t+2000,onEvents:rows=>emitted.push(...rows),call:async(method,params)=>{if(method==='getSignaturesForAddress'){assert.equal(params[1].commitment,'finalized');return [{signature:'bad',blockTime:t/1000,slot:101},{signature:'good',blockTime:t/1000,slot:100}];}assert.equal(params[1].maxSupportedTransactionVersion,1);assert.equal(params[1].commitment,'finalized');if(params[0]==='bad')throw Error('RPC failure');return tx();}}),/RPC failure/);assert.equal(emitted.length,1);assert.equal(m.cursorSig,'good');assert.equal(m.lastBatch.complete,false);assert.equal(emitted[0].raw.firstObservedAt,t+2000);assert.equal(emitted[0].raw.tokenDecimals,6);});
test('null transactions retry without cursor loss, then explicitly quarantine instead of looping forever',async()=>{const m={mint,cursorSig:null},options={c:{sigPages:1,txPerPull:25},now:()=>t+2000,call:async method=>method==='getSignaturesForAddress'?[{signature:'null-tx',blockTime:t/1000}]:null};await pullMint(m,options);assert.equal(m.cursorSig,null);await pullMint(m,options);assert.equal(m.cursorSig,null);await pullMint(m,options);assert.equal(m.cursorSig,'null-tx');assert.ok(m.lastBatch.gaps.includes('quarantined-after-three-unavailable-reads'));assert.equal(m.lastBatch.complete,false);});
test('failed transactions never become swap evidence',()=>{const x=tx();x.meta.err={InstructionError:[0,'failure']};assert.deepEqual(parseSwapEvents(x,mint),[]);});
test('partial-depth fixtures use the shared simulator, never invent unlimited liquidity',()=>{const adapter=new MarketAdapter({venue:'fixture'}),market=adapter.normalize({timestamp:t,asks:[{price:1,quantity:2}],bids:[{price:.9,quantity:2}]},{now:t});const r=new OrderSimulator().simulate({order:{side:'BUY',quantity:5},market,friction:new FrictionModel({allowDepthPartial:true}),now:t});assert.equal(r.status,'PARTIAL');assert.equal(r.filledQuantity,2);assert.throws(()=>new OrderSimulator().simulate({mode:'LIVE'}),/simulation-only/);});
test('crowd quote requests share the existing cap even if study protocol changes',async()=>{const dir=fs.mkdtempSync(path.join(root,'quotes-')),now=Date.now();fs.writeFileSync(path.join(dir,'wallet-crowd-requests.json'),JSON.stringify({schema:CROWD_SCHEMA,mode:'PAPER',liveExecutionAllowed:false,protocolHash:'new-crowd',expiresAt:now+60000,requests:[{mint,side:'BUY',amountRaw:'10000000',submittedAt:now,expiresAt:now+60000}]}));fs.writeFileSync(path.join(dir,'pump-profit-quotes.json'),JSON.stringify({protocolHash:'prior-study',calls:4096,quotes:[],errors:[],callsThisHour:0,hour:Math.floor(now/3600000),backoffUntil:0,lastCallAt:0}));let calls=0;const r=await collectPumpProfitQuotes({dir,now,sleep:async()=>{},fetchImpl:async()=>{calls++;throw Error('must not call');}});assert.equal(calls,0);assert.equal(r.calls,0);});
test('common horizon includes deliberate NO TRADE as zero and leaves open exits unknown',async()=>{
 const {settleCommonComparisons}=await import('../src/crowdStudy.js');const s=study(),b=openDirect(s,2);
 const at=s.decisions[0].evaluationDueAt+1;settleCommonComparisons(s,at);assert.equal(s.comparisons[0].complete,false);assert.equal(s.comparisons[0].results.CROWD_AWARE.netSol,0);assert.equal(s.comparisons[0].results.DIRECT_COPY.netSol,null);
 for(const book of s.cohorts[0].books){book.positions=[];book.pending=[];if(['BASELINE','DIRECT_COPY'].includes(book.candidateId))book.history.push({id:book.id+':'+s.decisions[0].eventId,pnlSol:-.02,sizeSol:.05,feesSol:.00001});}
 settleCommonComparisons(s,at+1);assert.equal(s.comparisons[0].complete,true);assert.equal(s.comparisons[0].copyDelta,.02);assert.equal(s.comparisons[0].allCostsKnown,false);
});

test('Command Center panel renders bounded unknown values safely and declares all three modes',async()=>{
 const vm=await import('node:vm'),source=fs.readFileSync(new URL('../public/js/wallet-crowd.js',import.meta.url),'utf8'),context={window:{},document:{addEventListener(){}},console};vm.runInNewContext(source,context);
 const html=context.window.mpoWalletCrowdHTML({collectorFresh:false,evaluation:{state:'<script>x</script>'}},true);assert.match(html,/Observe Only/);assert.match(html,/Shadow Comparison/);assert.match(html,/Opt-In Paper Experiment/);assert.match(html,/&lt;script&gt;/);assert.doesNotMatch(html,/<script>x/);assert.match(html,/Unknown/);
 const files=[new URL('../public/dashboard.html',import.meta.url),new URL('../../money-printer-evolution-lab/public/lab.html',import.meta.url)];for(const file of files){if(!fs.existsSync(file))continue;for(const match of fs.readFileSync(file,'utf8').matchAll(/<script(?![^>]*src=)[^>]*>([\s\S]*?)<\/script>/g)){if(match[1].trim())new vm.Script(match[1]);}}
});
