import fs from 'node:fs';
import path from 'node:path';
import { edgeProofSnapshot } from './edgeProof.js';
import { alphaInsightsSnapshot, writeAlphaInsights } from './alphaInsights.js';
import { alphaDbSnapshot } from './alphaDb.js';
const DIR=path.resolve(process.env.MONEY_PRINTER_DATA_DIR || 'data', 'reports');
export function buildDailyAlphaReport(){let insights=alphaInsightsSnapshot();if(insights.status==='UNAVAILABLE')insights=writeAlphaInsights();const proof=edgeProofSnapshot(),db=alphaDbSnapshot(),top=insights.leaderboard?.[0]||null,timing=insights.delayedEntry||{},cal=insights.calibration||{};return{generatedAt:Date.now(),edgeVerdict:proof.status,proofScore:proof.proofScore,independentMints:proof.independentMints,nextAction:proof.nextAction,strongestAlpha:top,bestEntryDelaySec:timing.bestDelaySec,delayedEntry:timing.rows||[],executionCalibration:cal,dbStats:db.stats,blockers:proof.blockers||[],latency:proof.latency||{}}}
export function writeDailyAlphaReport(){const r=buildDailyAlphaReport(),d=new Date(r.generatedAt).toISOString().slice(0,10);fs.mkdirSync(DIR,{recursive:true});fs.writeFileSync(path.join(DIR,`${d}-alpha.json`),JSON.stringify(r,null,2));const lines=[`# Money Printer Engine 12.6 Alpha Report — ${d}`,'',`**EDGE:** ${r.edgeVerdict} (${r.proofScore}%)`,`**Independent 30m launches:** ${r.independentMints}`,`**Next action:** ${r.nextAction}`,'',`## Strongest alpha`,r.strongestAlpha?`- ${r.strongestAlpha.title} (${r.strongestAlpha.regime}) — lower CI ${Number(r.strongestAlpha.lowerCiPct||0).toFixed(2)}%, recent delta ${Number(r.strongestAlpha.recentDeltaPct||0).toFixed(2)}%, ${r.strongestAlpha.decay}`:'- None validated yet.','',`## Entry timing`,`- Best measured delay: ${r.bestEntryDelaySec==null?'collecting':r.bestEntryDelaySec+'s'}`,...r.delayedEntry.map(x=>`- +${x.delaySec}s: n=${x.samples}, avg adjusted ${Number(x.avgAdjustedPct||0).toFixed(2)}%, vs NOW ${Number(x.improvementVsNowPct||0).toFixed(2)}%`),'',`## Execution calibration`,`- ${r.executionCalibration.status} — n=${r.executionCalibration.samples||0}`,'',`## Current blockers`,...(r.blockers.length?r.blockers.map(x=>`- ${x}`):['- None']),'' ];fs.writeFileSync(path.join(DIR,`${d}-alpha.md`),lines.join('\n'));fs.writeFileSync(path.resolve(process.env.MONEY_PRINTER_DATA_DIR || 'data', 'latest-alpha-report.json'),JSON.stringify(r,null,2));return r}
if(import.meta.url===`file://${process.argv[1]}`){const r=writeDailyAlphaReport();console.log(JSON.stringify(r,null,2))}
