import { loadState, saveState } from './store.js';
import { ensureResearch, nightlyResearch, evolutionSnapshot, generateExperiment, strategyMutation, calibrate } from './research.js';
const s = loadState();
ensureResearch(s);
generateExperiment(s);
strategyMutation(s);
calibrate(s);
nightlyResearch(s);
s.evolution = evolutionSnapshot(s);
saveState(s);
console.log('\nMONEY PRINTER OS V8 // EVOLUTION LAB');
console.log('Autonomy level:', s.research.autonomyLevel);
console.log('Champion:', s.research.champion);
console.log('Running experiments:', s.research.experiments.filter(x => x.status === 'RUNNING').length);
console.log('Challengers:', s.research.challengers.length);
console.log('Lessons:', s.research.lessons.length);
console.log('Postmortems:', s.research.postmortems.length);
console.log('Model health:', s.research.modelHealth);
console.table(s.evolution.tournament.slice(0, 12));
