const clamp=(x,a=0,b=100)=>Math.max(a,Math.min(b,x));
const n=x=>Number(x||0);
export function pushTick(state,a){state.tickHistory=state.tickHistory||{};const xs=state.tickHistory[a.mint]||(state.tickHistory[a.mint]=[]);xs.push({ts:Date.now(),price:a.priceUsd,liq:a.liq,v5:a.v5,flow:a.flow5,score:a.score,buys:a.b5,sells:a.s5});if(xs.length>180)xs.splice(0,xs.length-180);return xs}
export function microFeatures(xs=[]){if(xs.length<2)return{p5:0,p10:0,p30:0,velocity:0,flowAccel:0,liqVelocity:0};const last=xs.at(-1),priceAgo=ms=>{const t=last.ts-ms;let x=xs[0];for(const q of xs){if(q.ts<=t)x=q;else break}return x};const ret=ms=>{const x=priceAgo(ms);return x?.price?((last.price/x.price)-1)*100:0};const prev=xs.at(-2);const dt=Math.max(1,(last.ts-prev.ts)/1000);return{p5:ret(5000),p10:ret(10000),p30:ret(30000),velocity:(n(last.buys)-n(prev.buys))/dt,flowAccel:(n(last.flow)-n(prev.flow))/dt,liqVelocity:prev.liq?((n(last.liq)/n(prev.liq))-1)*100/dt:0}}
export function explosionScore(a,m={}){return Math.round(clamp(a.bestStrategyScore*.28+Math.max(a.pc5,0)*.8+Math.max(m.p30,0)*1.6+Math.max(m.velocity,0)*8+Math.max(m.flowAccel,0)*12+Math.max(a.volumeDelta,0)*.08+Math.max(a.liqDelta,0)*.12))}
export function moonScore(a,m={}){const upside=explosionScore(a,m),risk=100-(a.risk?.score??50);return Math.round(clamp(upside*.78+risk*.22))}
export function buildCandles(xs=[],bucketMs=15000){const map=new Map();for(const x of xs){const k=Math.floor(x.ts/bucketMs)*bucketMs;const c=map.get(k)||{ts:k,o:x.price,h:x.price,l:x.price,c:x.price,liq:x.liq};c.h=Math.max(c.h,x.price);c.l=Math.min(c.l,x.price);c.c=x.price;c.liq=x.liq;map.set(k,c)}return [...map.values()].slice(-40)}
export function narrative(symbol='',name=''){const s=(symbol+' '+name).toLowerCase(),tags=[];for(const [k,ws] of Object.entries({AI:['ai','gpt','agent','robot'],ANIMAL:['dog','cat','frog','pepe','monkey','ape','goat'],POLITICS:['trump','president','maga','vote'],GAMING:['game','gaming','pixel','npc'],CELEB:['elon','musk','kanye','taylor'],MEME:['meme','wojak','chad','bonk']}))if(ws.some(w=>s.includes(w)))tags.push(k);return tags.length?tags:['OTHER']}
export function walletSignals(risk){if(!risk)return[];const out=[];if(risk.top1Pct>20)out.push('WHALE_HEAVY');if(risk.top10Pct>60)out.push('CLUSTERED_SUPPLY');if(risk.mintAuthority)out.push('MINT_CONTROL');if(risk.freezeAuthority)out.push('FREEZE_CONTROL');return out}
