import {VersionedTransaction,Keypair,Connection,LAMPORTS_PER_SOL} from '@solana/web3.js';
import bs58 from 'bs58';
import {cfg} from './config.js';
import {tokenBalanceRaw} from './rpc.js';
import {jitoSendTransaction} from './providers.js';
import {withTimeout} from './utils.js';
const SOL='So11111111111111111111111111111111111111112',api='https://api.jup.ag/swap/v2';
function auth(){if(!cfg.jupiterApiKey)throw new Error('Missing JUPITER_API_KEY');return{'x-api-key':cfg.jupiterApiKey,accept:'application/json'}}
export function wallet(){if(!cfg.privateKey)throw new Error('Missing BS58_PRIVATE_KEY');return Keypair.fromSecretKey(bs58.decode(cfg.privateKey))}
export function walletAddress(){return wallet().publicKey.toBase58()}
export async function walletSolBalance(){const kp=wallet(),c=new Connection(cfg.rpcUrl,'confirmed');return(await withTimeout(c.getBalance(kp.publicKey),5500,'wallet SOL balance'))/LAMPORTS_PER_SOL}
async function order(inputMint,outputMint,amount){const kp=wallet(),u=new URL(`${api}/order`);u.searchParams.set('inputMint',inputMint);u.searchParams.set('outputMint',outputMint);u.searchParams.set('amount',String(amount));u.searchParams.set('taker',kp.publicKey.toBase58());if(Number(cfg.maxSlippageBps)>0)u.searchParams.set('slippageBps',String(Math.round(cfg.maxSlippageBps)));const r=await withTimeout(fetch(u,{headers:auth()}),7000,'Jupiter order');if(!r.ok)throw new Error(`Jupiter order ${r.status}: ${(await r.text()).slice(0,500)}`);return r.json()}
async function signExecute(o){if(!o.transaction)throw new Error('Jupiter returned no transaction');const kp=wallet(),tx=VersionedTransaction.deserialize(Buffer.from(o.transaction,'base64'));tx.sign([kp]);const signedTransaction=Buffer.from(tx.serialize()).toString('base64');if(cfg.jitoEnabled)return jitoSendTransaction(signedTransaction);const r=await withTimeout(fetch(`${api}/execute`,{method:'POST',headers:{...auth(),'content-type':'application/json'},body:JSON.stringify({signedTransaction,requestId:o.requestId,lastValidBlockHeight:o.lastValidBlockHeight})}),9000,'Jupiter execute');const body=await r.json().catch(()=>({}));if(!r.ok||body.status==='Failed')throw new Error(`Jupiter execute failed: ${JSON.stringify(body).slice(0,800)}`);return body}
export async function buyWithSol(outputMint,solAmount){const owner=walletAddress(),before=(await tokenBalanceRaw(owner,outputMint).catch(()=>({raw:0n}))).raw;const result=await signExecute(await order(SOL,outputMint,Math.floor(solAmount*LAMPORTS_PER_SOL)));let acquired=0n;for(let i=0;i<6;i++){await new Promise(r=>setTimeout(r,700));const after=(await tokenBalanceRaw(owner,outputMint).catch(()=>({raw:before}))).raw;acquired=after-before;if(acquired>0n)break}return{...result,acquiredRaw:acquired.toString()}}
export async function sellTokenForSol(inputMint,rawAmount){const before=await walletSolBalance().catch(()=>null);const result=await signExecute(await order(inputMint,SOL,rawAmount));let receivedSol=null;if(before!=null){for(let i=0;i<6;i++){await new Promise(r=>setTimeout(r,700));const after=await walletSolBalance().catch(()=>null);if(after!=null&&after>before){receivedSol=after-before;break}}}return{...result,receivedSol}}
