import { loadEdgeGate } from './edgeGate.js';
const clamp = (x, a = 0, b = 1) => Math.max(a, Math.min(b, Number(x) || 0));
const FEATURES = ['edge','explosion','execution','momentum','liquidity','freshness','flow','volumeAccel','priceAccel'];
const DEFAULT_WEIGHTS = { edge:.28, explosion:.20, execution:.16, momentum:.10, liquidity:.08, freshness:.04, flow:.06, volumeAccel:.04, priceAccel:.04 };
const HORIZONS = [5, 30, 120];
const MIN_SAMPLES = 40;

function norm(a) {
  return {
    edge: clamp((a.edgeScore ?? a.score) / 100), explosion: clamp((a.explosionScore || 0) / 100),
    execution: clamp((a.executionScore || 0) / 100), momentum: clamp((a.momentumScore || 0) / 100),
    liquidity: clamp((a.liquidityScore || 0) / 100), freshness: clamp((a.freshnessScore || 0) / 100),
    flow: clamp((Number(a.flow5 || 1) - .5) / 2.5), volumeAccel: clamp((Number(a.volumeDelta || 0) + 50) / 150),
    priceAccel: clamp((Number(a.priceAccel || 0) + 20) / 60),
  };
}
export function evolutionChampionPolicy(s){
  if(s?.labLink && !s.labLink.connected)return null;
  const c=s?.evolutionLoop?.champion,v=c?.variant,m=c?.metrics||{};
  if(!v||!c?.id||c.id==='BASE'||!['SHADOW','PAPER_CANARY','PAPER'].includes(String(c.stage||'')))return null;
  if(!['heldOutN','samples','activityPct','monteCarloPassPct','stressAvgPct','consistencyPct'].every(k=>m[k]!=null&&Number.isFinite(Number(m[k]))))return null;
  if(['threshold','stopPct','takePct','maxHoldMin'].some(k=>v[k]!=null&&(!Number.isFinite(Number(v[k]))||Number(v[k])<=0)))return null;
  if(v.weights && (typeof v.weights!=='object'||!FEATURES.every(k=>Number.isFinite(Number(v.weights[k]??0))&&Number(v.weights[k]??0)>=0)||!FEATURES.some(k=>Number(v.weights[k])>0)))return null;
  if(Number(m.heldOutN||0)<12||Number(m.samples||0)<40||Number(m.activityPct||0)<8||Number(m.monteCarloPassPct||0)<70||Number(m.stressAvgPct||0)<-2||Number(m.consistencyPct||0)<50)return null;
  return{id:c.id,sourceStage:c.stage,threshold:Math.max(20,Math.min(95,Number(v.threshold||60))),stopPct:Math.max(.5,Number(v.stopPct||8)),takePct:Math.max(1,Number(v.takePct||16)),maxHoldMin:Math.max(1,Number(v.maxHoldMin||30)),weights:v.weights||DEFAULT_WEIGHTS,promotedAt:Number(c.promotedAt||0)};
}
export function evolutionChampionScore(s,a){const p=evolutionChampionPolicy(s);if(!p)return null;const f=norm(a),score=FEATURES.reduce((q,k)=>q+Number(p.weights[k]||0)*Number(f[k]||0),0)*100;return{...p,score:Math.round(clamp(score/100)*100)}}
const blankStats = () => Object.fromEntries(FEATURES.map(k => [k, { n:0, sx:0, sy:0, sxx:0, syy:0, sxy:0 }]));
function horizonState(){return Object.fromEntries(HORIZONS.map(h=>[h,{samples:0,trainingSamples:0,validationSamples:0,validated:false,validationSpreadPct:0,featureStats:blankStats(),weights:{...DEFAULT_WEIGHTS},correlations:{},clusterCounts:{}}]));}

export function ensureLearner(s) {
  s.research ||= {};
  s.research.learner ||= {version:2, weights:{...DEFAULT_WEIGHTS}, pending:[], outcomes:[], featureStats:blankStats(), samples:0, trainingSamples:0, validationSamples:0, validated:false, validationSpreadPct:0, lastUpdate:0, status:'COLLECTING', lastCorrelation:{}, horizons:horizonState()};
  const l=s.research.learner;
  l.version=2; l.pending ||= []; l.outcomes ||= []; l.horizons ||= horizonState();
  for(const h of HORIZONS){ l.horizons[h] ||= horizonState()[h]; const hs=l.horizons[h]; hs.featureStats ||= blankStats(); hs.weights ||= {...DEFAULT_WEIGHTS}; hs.correlations ||= {}; hs.clusterCounts ||= {}; for(const k of FEATURES){hs.featureStats[k] ||= {n:0,sx:0,sy:0,sxx:0,syy:0,sxy:0};hs.weights[k] ??= DEFAULT_WEIGHTS[k];}}
  l.trainingSamples ??= 0; l.validationSamples ??= 0; l.validated ??= false; l.validationSpreadPct ??= 0;
  for(const k of FEATURES){l.weights[k] ??= DEFAULT_WEIGHTS[k]; l.featureStats[k] ||= {n:0,sx:0,sy:0,sxx:0,syy:0,sxy:0};}
  // Migrate old single-horizon pending records in-place.
  for(const p of l.pending){ if(!Array.isArray(p.horizons)){p.horizons=HORIZONS.map(min=>({min,dueAt:Number(p.ts||Date.now())+min*60_000,settled:false})); delete p.dueAt;} }
  return l;
}
function corr(st){const n=st.n||0;if(n<8)return 0;const num=n*st.sxy-st.sx*st.sy;const den=Math.sqrt(Math.max(1e-12,(n*st.sxx-st.sx**2)*(n*st.syy-st.sy**2)));return den?num/den:0;}
function normalizeWeights(weights){const clean={};let total=0;for(const k of FEATURES){clean[k]=Math.max(.015,Number(weights[k]||0));total+=clean[k];}for(const k of FEATURES)clean[k]/=total||1;return clean;}
function validationSplit(key=''){let h=2166136261;for(let i=0;i<key.length;i++){h^=key.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0)%5===0;}
function rawScore(weights,features={}){let q=0;for(const k of FEATURES)q+=Number(weights[k]||0)*Number(features[k]||0);return q*100;}
function refreshValidation(l, horizon){const hs=l.horizons[horizon];const rows=l.outcomes.filter(x=>x.isValidation&&x.horizonMin===horizon).slice(0,500);hs.validationSamples=rows.length;if(rows.length<30){hs.validated=false;hs.validationSpreadPct=0;return;}const scored=rows.map(x=>({...x,modelScore:rawScore(hs.weights,x.features)})).sort((a,b)=>b.modelScore-a.modelScore);const n=Math.max(5,Math.floor(scored.length*.25));const avg=xs=>xs.length?xs.reduce((q,x)=>q+Number(x.returnPct||0),0)/xs.length:0;hs.validationSpreadPct=avg(scored.slice(0,n))-avg(scored.slice(-n));hs.validated=hs.validationSpreadPct>1.0;}

export function fastEdgeScore(s,a){const l=ensureLearner(s),x=norm(a);let baseline=Number(a.edgeScore??a.score??0);const gate=loadEdgeGate();if(!gate.productionLearningUnlocked)return Math.round(baseline);const approved=new Set(gate.approvedHorizons||[]);const validated=HORIZONS.filter(h=>approved.has(h)&&l.horizons[h]?.validated&&l.horizons[h]?.trainingSamples>=MIN_SAMPLES);if(!validated.length)return Math.round(baseline);let learned=0,total=0;for(const h of validated){const weight=h===5?.50:h===30?.32:.18;learned+=rawScore(l.horizons[h].weights,x)*weight;total+=weight;}learned/=total||1;const sample=Math.min(...validated.map(h=>l.horizons[h].trainingSamples));const blend=Math.min(.42,.10+(sample-MIN_SAMPLES)/1600);return Math.round(clamp((baseline*(1-blend)+learned*blend)/100)*100);}

export function queueOutcomeSamples(s,ranked=[]){const l=ensureLearner(s),now=Date.now(),existing=new Set(l.pending.map(x=>x.key)),bucket=Math.floor(now/300_000),recentMint=new Map();for(const x of [...l.pending,...l.outcomes.slice(0,1000)]){recentMint.set(x.mint,Math.max(recentMint.get(x.mint)||0,Number(x.ts||x.entryTs||0)))}for(const a of ranked.slice(0,30)){if(!a?.mint||!(Number(a.priceUsd)>0))continue;if(now-(recentMint.get(a.mint)||0)<4*60_000)continue;const key=`${a.mint}:${bucket}`;if(existing.has(key))continue;l.pending.push({key,mint:a.mint,symbol:a.symbol,ts:now,price:Number(a.priceUsd),features:norm(a),fastEdge:Number(a.fastEdgeScore||a.edgeScore||a.score||0),stage:a.stage,entryThreshold:Number(a.entryThreshold||60),context:{regime:a.regime||'UNKNOWN',liquidity:Number(a.liq||0),execution:Number(a.executionScore||0),clusterId:a.risk?.mintAuthority||null},horizons:HORIZONS.map(min=>({min,dueAt:now+min*60_000,settled:false}))});}if(l.pending.length>3000)l.pending=l.pending.slice(-3000);}
export function dueOutcomeMints(s,ranked=[],limit=90){const l=ensureLearner(s),now=Date.now(),seen=new Set((ranked||[]).map(a=>a?.mint).filter(Boolean));return[...new Set(l.pending.filter(p=>(p.horizons||[]).some(h=>!h.settled&&h.dueAt<=now)&&!seen.has(p.mint)).map(p=>p.mint))].slice(0,limit);}

function updateHorizon(l,p,horizon,retPct,isValidation,now,price){const hs=l.horizons[horizon];const y=Math.max(-1,Math.min(1,retPct/(horizon===5?35:horizon===30?75:150)));const cluster=String(p.context?.clusterId||p.mint||'unknown'),clusterN=Number(hs.clusterCounts?.[cluster]||0),allowTraining=!isValidation&&clusterN<20;if(allowTraining){for(const k of FEATURES){const x=Number(p.features[k]||0),st=hs.featureStats[k];st.n++;st.sx+=x;st.sy+=y;st.sxx+=x*x;st.syy+=y*y;st.sxy+=x*y;}hs.trainingSamples++;hs.clusterCounts[cluster]=clusterN+1;}hs.samples++;l.outcomes.unshift({ts:now,entryTs:Number(p.ts||0),sampleKey:p.key,mint:p.mint,symbol:p.symbol,horizonMin:horizon,entryPrice:p.price,exitPrice:price,returnPct:retPct,predicted:p.fastEdge,stage:p.stage,entryThreshold:p.entryThreshold,features:p.features,context:p.context||{},isValidation});const raw={};for(const k of FEATURES){const r=corr(hs.featureStats[k]);hs.correlations[k]=r;raw[k]=.025+Math.max(-.15,r)+DEFAULT_WEIGHTS[k]*.65;}const target=normalizeWeights(raw),rate=Math.min(.06,.012+1/Math.max(80,hs.trainingSamples));for(const k of FEATURES)hs.weights[k]=hs.weights[k]*(1-rate)+target[k]*rate;hs.weights=normalizeWeights(hs.weights);refreshValidation(l,horizon);}

export function settleOutcomeSamples(s,ranked=[],extraPrices=new Map()){const l=ensureLearner(s),now=Date.now(),prices=new Map(ranked.filter(a=>a?.mint&&Number(a.priceUsd)>0).map(a=>[a.mint,Number(a.priceUsd)])),fresh=new Set(ranked.filter(a=>a?.mint&&Number(a.priceUsd)>0).map(a=>a.mint));for(const[mint,price]of extraPrices||[])if(Number(price)>0){prices.set(mint,Number(price));fresh.add(mint);}const remain=[];let settled=0;for(const p of l.pending){const price=prices.get(p.mint)||Number(s.research?.universe?.[p.mint]?.lastPrice||0),lastSeen=Number(s.research?.universe?.[p.mint]?.lastSeen||0);for(const h of p.horizons||[]){if(h.settled||h.dueAt>now)continue;const maxLateMs=(h.min===5?3:h.min===30?10:30)*60_000;if(now-h.dueAt>maxLateMs){h.settled=true;h.missed=true;continue;}if(!(price>0)||(!fresh.has(p.mint)&&now-lastSeen>90_000))continue;const retPct=(price/p.price-1)*100;updateHorizon(l,p,h.min,retPct,validationSplit(`${p.context?.clusterId||p.mint}:${h.min}`),now,price);h.settled=true;settled++;}const unresolved=(p.horizons||[]).some(h=>!h.settled);const oldestDue=Math.min(...(p.horizons||[]).filter(h=>!h.settled).map(h=>h.dueAt),Infinity);if(unresolved&&now-oldestDue<6*60*60_000)remain.push(p);}l.pending=remain;l.outcomes=l.outcomes.slice(0,6000);if(settled){const h5=l.horizons[5];l.samples=HORIZONS.reduce((q,h)=>q+l.horizons[h].samples,0);l.trainingSamples=h5.trainingSamples;l.validationSamples=h5.validationSamples;l.validated=h5.validated;l.validationSpreadPct=h5.validationSpreadPct;l.weights={...h5.weights};l.lastCorrelation={...h5.correlations};l.lastUpdate=now;const v=HORIZONS.filter(h=>l.horizons[h].validated);l.status=v.length===3?'MULTI-HORIZON VALIDATED':v.length?'PARTIALLY VALIDATED':h5.trainingSamples>=MIN_SAMPLES?'HOLDOUT REVIEW':'COLLECTING';}return settled;}
export function learnerSnapshot(s){const l=ensureLearner(s);const horizon={};for(const h of HORIZONS){const rows=l.outcomes.filter(x=>x.horizonMin===h).slice(0,250),avg=rows.length?rows.reduce((q,x)=>q+x.returnPct,0)/rows.length:0,hit25=rows.length?rows.filter(x=>x.returnPct>=25).length/rows.length*100:0,hit100=rows.length?rows.filter(x=>x.returnPct>=100).length/rows.length*100:0;horizon[h]={samples:l.horizons[h].samples,trainingSamples:l.horizons[h].trainingSamples,validationSamples:l.horizons[h].validationSamples,validated:l.horizons[h].validated,validationSpreadPct:l.horizons[h].validationSpreadPct,avgReturnPct:avg,hit25Pct:hit25,hit100Pct:hit100};}return{status:l.status,samples:l.samples,pending:l.pending.length,lastUpdate:l.lastUpdate,horizons:horizon,validatedHorizons:HORIZONS.filter(h=>l.horizons[h].validated),weights:l.weights,correlations:l.lastCorrelation,recentAvg5mPct:horizon[5].avgReturnPct,recentHit25Pct:horizon[5].hit25Pct};}
