import {cfg} from './config.js';
// User-facing strategy zoo removed. The engine has one objective; individual signals are features.
export const strategyNames=['UNIFIED_EDGE'];
export const operatingProfiles={CALM:{aggression:55,exitPreset:'custom',entryFrequency:'normal'},FAST:{aggression:72,exitPreset:'scalper',entryFrequency:'high'},DEGEN:{aggression:86,exitPreset:'runner',entryFrequency:'high'},MAX:{aggression:96,exitPreset:'yolo',entryFrequency:'max'},FAIR:{aggression:72,exitPreset:'fair',entryFrequency:'normal'},SPRINT:{aggression:100,exitPreset:'sprint',entryFrequency:'max'},RESEARCH:{aggression:100,exitPreset:'runner',entryFrequency:'max'},AGGRESSIVE_PAPER:{aggression:98,entryFrequency:'max',maxOpenPositions:25,paperOverrides:{tradeSizeSol:1.0,maxPositionSol:3.0,maxTotalExposureSol:10.0,dailyLossLimitSol:5.0}}};
export const isAggressivePaper=(runtime,mode=cfg.mode)=>mode==='paper'&&String(runtime?.profile||'').toUpperCase()==='AGGRESSIVE_PAPER';
// These profiles share the existing controls; exploratory books carry their own funded limits.
operatingProfiles.FAST_PAPER_STEADY={aggression:72,exitPreset:'fair',entryFrequency:'high',researchMode:'FAST_PAPER_STEADY',paperLanes:{arbitrage:true,nativeSniper:false},paidModelCalls:0};
operatingProfiles.BURST_RESEARCH={...operatingProfiles.FAST_PAPER_STEADY,researchMode:'BURST_RESEARCH'};
export function paperLaneEnabled(runtime,lane,mode=cfg.mode){return mode==='paper'&&(runtime?.paperLanes?.[lane]===true||isAggressivePaper(runtime,mode));}
export function defaults(){return{profile:'FAIR',aggression:72,maxCandidates:cfg.maxCandidates,entryFrequency:'normal',exitPreset:'fair',followLabBest:true,controlMode:'LAB_AUTO',strategies:{UNIFIED_EDGE:true},favorites:[],blacklist:[],pinned:[],visualIntensity:90,autonomyLevel:4,workspace:'TRADE'}}
export function aggressionParams(v){v=Math.max(0,Math.min(100,Number(v)||0));return{minScore:Math.round(70-v*.38),minStrategyScore:Math.round(68-v*.36),maxOpenPositions:Math.max(1,Math.round(1+v/15)),sizeFactor:.25+v/95,allowWarnings:v>=20}}
// User-editable exits for exitPreset 'custom' and a manual open-position cap. Bounds are hard; anything else is dropped.
export const customExitBounds={tp1:[1,200],tp2:[1,500],stop:[1,50],trail:[1,50],maxHold:[1,720]};
export const MAX_OPEN_OVERRIDE=[1,30];
export function sanitizeCustomExit(raw){const out={};if(!raw||typeof raw!=='object')return out;for(const [k,[lo,hi]] of Object.entries(customExitBounds)){const n=Number(raw[k]);if(raw[k]!==''&&raw[k]!=null&&Number.isFinite(n))out[k]=Math.max(lo,Math.min(hi,k==='maxHold'?Math.round(n):n))}return out}
export function customExitPolicy(runtime){return{tp1:cfg.takeProfit1Pct,tp2:cfg.takeProfit2Pct,stop:cfg.stopLossPct,trail:cfg.trailingStopPct,maxHold:cfg.maxHoldMin,...sanitizeCustomExit(runtime?.customExit)}}
export function openLimitFor(runtime,mode=cfg.mode){const ap=aggressionParams(runtime?.aggression),o=Number(runtime?.maxOpenPositions),manual=Number.isInteger(o)&&o>=MAX_OPEN_OVERRIDE[0]&&o<=MAX_OPEN_OVERRIDE[1]?o:null,base=manual??ap.maxOpenPositions;if(mode!=='paper')return Math.min(base,cfg.maxOpenPositions);return isAggressivePaper(runtime,mode)?25:runtime?.profile==='SPRINT'?Math.max(16,base):base}
export const exitPresets={ultraScalp:{tp1:3,tp2:7,stop:4,trail:3,maxHold:10},sprint:{tp1:4,tp2:14,stop:5,trail:5,maxHold:25},fair:{tp1:12,tp2:30,stop:8,trail:7,maxHold:90},scalper:{tp1:7,tp2:14,stop:7,trail:5,maxHold:25},runner:{tp1:15,tp2:35,stop:10,trail:9,maxHold:120},moonbag:{tp1:18,tp2:50,stop:12,trail:12,maxHold:240},yolo:{tp1:25,tp2:80,stop:18,trail:15,maxHold:360},custom:null};
